#!C:\SpinyLeaf_APP_Dep\WPy64-31190b5\python-3.11.9.amd64\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
